services:
  web:
    build: .
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    networks:
      database:
        ipv4_address: 10.105.10.2
    depends_on:
      - db
      - migration

  migration:
    build: .
    volumes:
      - ./:/src
    command: ./manage.py migrate
    networks:
      database:
        ipv4_address: 10.105.10.4
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: "default"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secure@password@for@root"
    networks:
      database:
        ipv4_address: 10.105.10.3

networks:
  database:
    driver: bridge
    ipam:
      config:
        - subnet: 10.105.10.0/24
          gateway: 10.105.10.1