# Generated by Django 5.0.6 on 2024-06-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=255)),
                ('goods_price', models.IntegerField()),
                ('goods_description', models.TextField()),
                ('goods_image', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsWithAttributesValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_warehouse', models.IntegerField()),
                ('attribute_value', models.IntegerField()),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributes')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.goods')),
            ],
        ),
    ]
